### ISSUE TITLE
Reset the result field after clearing value in input amount

### ISSUE THREAD

**Issue by JB1905** [xxczaki/currency-converter#2]
<img width="510" alt="Zrzut ekranu 2020-03-23 o 18 07 03" src="https://user-images.githubusercontent.com/28870390/77342892-2af8e080-6d31-11ea-8979-dfcbbdd8cb88.png">

**Comment by xxczaki** [comment]
Thanks for reporting this issue. I fixed it in 
d6cb9e8 :smile:
